AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Equipment Restful API.


Globals:

  Function:
    Runtime: java8
    Environment:
      Variables:
        TABLE_NAME: !Ref Table

  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"


Resources:

  CreateEquipmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.equipment.CreateEquipmentHandler::handleRequest
      CodeUri: build/distributions/EquipmentAPI.zip
      FunctionName: CreateEquipmentFunction
      Policies: AmazonDynamoDBFullAccess
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /api/equipment
            Method: POST

  GetEquipmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.equipment.GetEquipmentHandler::handleRequest
      CodeUri: build/distributions/EquipmentAPI.zip
      FunctionName: GetEquipmentFunction
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        GetByPathApi:
          Type: Api
          Properties:
            Path: /api/equipment/{equipmentNumber}
            Method: GET
        GetByQueryApi:
          Type: Api
          Properties:
            Path: /api/equipment/search
            Method: GET

  Table:
    Type: AWS::Serverless::SimpleTable
    TableName: Equipment
    Properties:
      PrimaryKey:
        Name: equipment_number
        Type: Number
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


Outputs:

  ApiUrl:
    Description: URL of the Prod stage of the API endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"